---
- hosts: all

  tasks:
    - include_role:
        name: 2do_parcial
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"


- name: Generar archivos y configurar sudoers
  hosts: all
  become: yes

  roles:
    - role_garciavera
